### ISSUE TITLE
Precommit hook fails when no related tests are found

### ISSUE THREAD

**Issue by ekh64** [spotify/web-scripts#1020]
I have a commit that updates a dependency and a single `jest.config.js` file. Because this is a `js` file, the following gets run and subsequently fails
```
$ jest --config jest.config.js --bail --findRelatedTests
No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
```

I propose adding  `--passWithNoTests` to the test stage in the pre-commit hooks to account for no related test files in a commit

**Comment by ekh64** [comment]
Soooo my repo has nonstandard tests (long story), and thus this fails every time we want to use `yarn commit`

**Comment by yuriteixeira** [comment]
Finally merged, sorry for such delay.
