### ISSUE TITLE
[web-scripts] postinstall should be "prepare"

### ISSUE THREAD

**Issue by kirbysayshi** [spotify/web-scripts#131]
I made a CLI tool that uses a very recent version of the web-scripts template. Default package.json has this in it:

```
"scripts": {
    "lint": "web-scripts lint",
    "test": "web-scripts test",
    "build": "web-scripts build",
    "commit": "web-scripts commit",
    "release": "web-scripts release",
    "postinstall": "web-scripts postinstall --threshold low"
  },
```

However, "postinstall" will trigger for anyone that uses this library, whether part of a cli tool, npx-installed, or part of a bigger library. This is bad because when you install a dependency, it's devDependencies are not installed! So `web-scripts` isn't present, which means any package made with the template is uninstallable!

I think we want it to be: `"prepare": "web-scripts postinstall --threshold low"`. From the docs:

> prepare: Run both BEFORE the package is packed and published, on local npm install without any arguments, and when installing git dependencies (See below). This is run AFTER prepublish, but BEFORE prepublishOnly.

"local npm install" means when developing.

**Comment by fastfrwrd** [comment]
very true, let's get that updated.
