### ISSUE TITLE
[tsconfig] Investigate using declarationMap to make source jumping easier

### ISSUE THREAD

**Issue by kirbysayshi** [spotify/web-scripts#17]
https://stackoverflow.com/a/51261384/169491

Apparently adding `declarationMap` to the declaration generation would allow for things like "Go To Definition" to take you to the actual TS instead of the type declaration when using a web-scripts-built module from another project!

**Comment by fastfrwrd** [comment]
Since it's for every `.d.ts` file [per the compiler options doc](https://www.typescriptlang.org/docs/handbook/compiler-options.html#compiler-options), it only needs to be added to the `types` build, right?

**Comment by kirbysayshi** [comment]
I believe so! But I haven't played around with it yet.

**Comment by fastfrwrd** [comment]
works like a charm!
