### ISSUE TITLE
[web-scripts] options "noEmit" and "incremental" are no longer allowed to be specified together

### ISSUE THREAD

**Issue by mtlewis** [spotify/web-scripts#215]
Looks like in Typescript 3.8, setting "noEmit" and "incremental" together cause build errors. I've worked around this in the repo I just upgraded, but we should probably update the tsconfigs in this repo to fit this new constraint. ~I suspect we probably want to turn off noEmit. I'll look at getting a PR up soon :).~ - just looked at the code, and I'm not sure it's as simple as I thought. I'll still try to get something up though! FWIW this actually bit me in the pre-commit task, so one of the changes might be to remove the `--noEmit` from [LintTask.ts](https://github.com/spotify/web-scripts/blob/master/packages/web-scripts/src/Tasks/LintTask.ts#L66).

cf. https://github.com/microsoft/TypeScript/issues/32882

**Comment by mtlewis** [comment]
OK - having looked at the tsconfigs in the repo in more detail, I don't think it makes sense for me to propose a change, since it sort of depends on the reason noEmit is there in the first place. Hopefully somebody with more historical context will be able to address this :)

**Comment by ekh64** [comment]
Echoing that I ran into this when upgrading `web-scripts`.

Talking with @fastfrwrd, he suggested modifying my `tsconfig.json` for the time being

```json
{
  "extends": "@spotify/web-scripts/config/tsconfig.json",
  "include": ["src"],
  "compilerOptions": {
    "incremental": false
  }
}
```
