### ISSUE TITLE
[tsconfig + eslint] "noUnusedLocals": false would be really nice

### ISSUE THREAD

**Issue by kirbysayshi** [spotify/web-scripts#218]
It's a huge pain to have `noUnusedLocals` set to `true` when refactoring, debugging, or generally when ever the code is not in a "complete" state. As an example, commenting out a function call temporarily to debug an issue will often cause a build failure because the imported  function is no longer used! It's just really a pain. 

While setting `"noUnusedLocals": false` puts more onus onto reviewers of codebases, this can be mitigated by causing the linter to fail on CI/CD (possibly precommit too) if unused locals are present.

**Comment by fastfrwrd** [comment]
we could potentially add this to the `--typecheck` lint target

**Comment by kirbysayshi** [comment]
It might be better set during build / `--watch`?

**Comment by fastfrwrd** [comment]
very similar ask here: https://github.com/spotify/web-scripts/issues/242
