### ISSUE TITLE
Cannot run tests against a single file

### ISSUE THREAD

**Issue by TychosDrunkElk** [spotify/web-scripts#219]
when I try to pass a single test file to web-scripts (`web-scripts test index.test.tsx` for example) I get the following error:
```
/node_modules/@spotify/web-scripts/cjs/index.js:42
    const { config } = cmd.opts();
                           ^

TypeError: cmd.opts is not a function
```

**Comment by fastfrwrd** [comment]
I'm unable to reproduce this - I've seen it in the past, but I wonder if a commander update has sorted it out since.

**Comment by fastfrwrd** [comment]
please comment or open a new issue if you see it again!
