### ISSUE TITLE
[eslint] Use warnings to signal lint issues that would be fine to ignore during watch mode

### ISSUE THREAD

**Issue by Rugvip** [spotify/web-scripts#242]
Hi, ran into an issue with combining `react-scripts` for bundling and serving an app together with the lint rules from `web-scripts`. https://github.com/spotify/backstage/issues/325

Do you think it makes sense to demote any rule to a warning that would be fine to ignore during watch/serve, but then not allow any warnings in the build task? Rules like no-console, no-unreachable, etc.

**Comment by kirbysayshi** [comment]
I'm for this, as long as it doesn't require us to maintain a separate set of lint rules. I also don't think we actually run lint during the build, so that is another problem we'd have to overcome!
