### ISSUE TITLE
`incremental` is not supported

### ISSUE THREAD

**Issue by kirbysayshi** [spotify/web-scripts#252]
If I'm understanding everything as reported by #215, using the `incremental` property at all will break web-script's lint step since it calls `tsc` with `--noEmit`.

We should probably explicitly mark `incremental` as `false` during the lint task to avoid this issue and allow users to use `incremental`.

Probably just a matter of adding `--incremental false` to https://github.com/spotify/web-scripts/blob/master/packages/web-scripts/src/Tasks/LintTask.ts#L66

Unless I'm misunderstanding the issue?

**Comment by kirbysayshi** [comment]
Another option is to include `--incremental` in the `build` and `watch` tasks.

**Comment by fastfrwrd** [comment]
@kirbysayshi that totally makes sense - we'll just want to add it everywhere where `noEmit` gets set in here?

**Comment by fastfrwrd** [comment]
it feels like maybe we should invert our thinking on `noEmit` a bit. Currently, `noEmit` is true by default, and is only flipped off for running `build`. But, many people set `noEmit`: false in their tsconfigs as a result, and wacky stuff starts happening. I think it may make more sense to:

- delete all of these instances of `noEmit`: https://github.com/spotify/web-scripts/search?q=noEmit&unscoped_q=noEmit
- update the lint typescript runs (pre-commit and lint) to have -`-noEmit true --incremental false` overrides on the CLI invocation.

**Comment by kirbysayshi** [comment]
@fastfrwrd yes, I think you're right. In general, we should probably make sure that each Task in web-scripts can be run successfully regardless of the details of tsconfig. So ensure each task's set of options is self-contained or perhaps overly-defined.
