### ISSUE TITLE
`web-scripts lint` doesn't accept --ignore-path

### ISSUE THREAD

**Issue by ekh64** [spotify/web-scripts#330]
I'm bumping my web-scripts from `6.2.0` to `7.0.0`, and in the process of working through the changes, I realized that my previous command: `web-scripts lint --config .eslintrc.js --ignore-path .gitignore` fails with the error: `Value for 'ignore-path' of type 'path::String' required.`

For context, I prefer to use `--ignore-path` over `.eslintignore` so that I can ignore all the files covered in the `.gitignore` in one place.

**Comment by jomaxx** [comment]
@ekh64 that's valid. 

the way some folks approach this is by creating a symlink for ignore files. if `.gitignore` is the source of truth then you can create `.eslintignore` to point to it. This also has the benefit of not needing to configure your IDE to know which ignore file to use.

let me know if a symlink would work for your projects.

**Comment by ekh64** [comment]
@jomaxx is this something no longer supported with the various bumps to `web-scripts`? I ask because it previously worked (6.2.0) and now doesn't seem to recognize `.gitignore` as a valid path string.

**Comment by jomaxx** [comment]
@ekh64 i'm not really sure what would've broken it but @fastfrwrd might know better

**Comment by fastfrwrd** [comment]
I am gonna guess it's an artifact of commander 4 => 5. It seems to work if you do `--ignore-path=.gitignore`, can you try that?

**Comment by ekh64** [comment]
@fastfrwrd yup, that did the trick! Now just some prettier stuff to deal with 😄

**Comment by fastfrwrd** [comment]
gonna close - this is unfortunate, but it sure makes me glad we put it in a breaking version.
