### ISSUE TITLE
`yarn bootstrap` isn't a valid command

### ISSUE THREAD

**Issue by ekh64** [spotify/web-scripts#361]
`web-scripts ^7.0.0`
I created a new project and added `web-scripts` as a single dev dependency. I wanted to bootstrap it, since I've never started a fresh project with `web-scripts`, and found that `yarn bootstrap` or `yarn run bootstrap` or even `yarn lerna run bootstrap` are invalid script commands.

For context, this is more of a side quest for my project. I mostly wanted to see if `yarn bootstrap` installed additional dependencies in the project that might fix https://github.com/spotify/web-scripts/issues/360

**Comment by fastfrwrd** [comment]
Hey! `yarn bootstrap` and `yarn lerna run bootstrap` are meant to bootstrap web-scripts itself as a developer of web-scripts; they aren't part of the public api.
