### ISSUE TITLE
[prettier] Add admonition support for markdown

### ISSUE THREAD

**Issue by fastfrwrd** [spotify/web-scripts#37]
We use `mkdocs` with the Material UI theme for docs internally, but the Markdown parser inside of Prettier doesn't know anything about [Admonitions](https://squidfunk.github.io/mkdocs-material/extensions/admonition/), which we use a lot of. We need to come up with a way to make it such that admonitions aren't broken by a prettier run.

The current bad behavior:
```markdown
<!-- before: -->
!!! info
    My cool admonition goes here!

<!-- after: -->
!!! info
My cool admonition goes here!
```

**Comment by alde** [comment]
Could we make prettier ignore .md files?

**Comment by fastfrwrd** [comment]
you can, but I feel it would be awesome to be able to use Prettier safely on markdown files. Today we can't, and unexpected stuff could happen.

**Comment by fastfrwrd** [comment]
we would disable it here if we wanted to turn it off: https://github.com/spotify/web-scripts/blob/master/packages/web-scripts/config/lint-staged.config.js#L28

**Comment by alde** [comment]
It could be a good first step, disable it until we can re-enable it without breaking

**Comment by boldmonkey** [comment]
You can prefix the admonition with `<!-- prettier-ignore -->` and Prettier will leave the formatting alone:

```
<!-- prettier-ignore -->
!!! info
    My cool admonition doesn't get messed up.
```

But... I'd love to see Prettier have native support for admonitions because the above is ugly.

**Comment by fastfrwrd** [comment]
This is a pretty Spotify-specific issue at this time. I think the workaround makes it pretty low priority.

**Comment by vilhelmprytz** [comment]
Any chance the need for this could be revaluated? Admonition support in Prettier wouldn't be too bad 🙂

**Comment by knulpi** [comment]
For everyone else stumbling upon an issue with prettier and mkdocs material, I recommend to use [prettiers range ignore](https://prettier.io/docs/en/ignore.html#range-ignore) with`<!-- prettier-ignore-start -->` and `<!-- prettier-ignore-end -->` sections. This will work even for content tabs in mkdocs.
