### ISSUE TITLE
default npm scripts should also include `prepublishOnly`

### ISSUE THREAD

**Issue by kirbysayshi** [spotify/web-scripts#38]
... and it should probably be something like:

```
"prepublishOnly": "web-scripts build"
```

Otherwise, when `release` occurs, such as via travisci or otherwise, there won't be any files to publish! Unless I'm wrong and semantic-release runs the `build` task?

**Comment by fastfrwrd** [comment]
the individual packages that need it have it, and lerna publish makes sure they get invoked: https://github.com/spotify/web-scripts/blob/master/packages/web-scripts/package.json#L29

**Comment by kirbysayshi** [comment]
Oh, sorry. I meant in the setup instructions for something that uses web-scripts!

**Comment by kirbysayshi** [comment]
We should have a recommendation of what is required there, such as in the travisci setup

**Comment by fastfrwrd** [comment]
Oh very true!!! Sorry for the misunderstanding

**Comment by kirbysayshi** [comment]
Nah, don't worry! I only now realize I wasn't clear in the initial issue :D
