### ISSUE TITLE
bug: latest version incorrectly detects imported types as unused vars

### ISSUE THREAD

**Issue by mtlewis** [spotify/web-scripts#555]
Hey folks! Running into an issue with the latest version of web-scripts, likely due to one or more of the packages that were indirectly upgraded. After this update, the linter now complains about imported types as unused vars. Here's a repository: https://github.com/mtlewis/web-scripts-repro that demonstrates the issue - try cloning and running `yarn lint`.

**Comment by kaimallea** [comment]
fixed by #570
