### ISSUE TITLE
[web-scripts] should `lint` task include stylelint?

### ISSUE THREAD

**Issue by kirbysayshi** [spotify/web-scripts#60]
Internally we used to have a custom stylelint config, but that was put aside as CSS-in-JS became more prevalent. stylelint can apparently extract CSS-in-JS and still apply linting, so it might be worth adopting the ["possible errors" config](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules.md#possible-errors) as the default.

**Comment by fastfrwrd** [comment]
Seems that we'd want to make it another optional parallel lint task inside of `web-scripts lint`, like typechecking, and then turn it on by default in a future major version.

**Comment by kirbysayshi** [comment]
Looks like we can promote / use the [recommended config](https://github.com/stylelint/stylelint-config-recommended) (possible errors) as the default too!
