### ISSUE TITLE
[bug] web-scripts precommit doesn't read specified eslint config file

### ISSUE THREAD

**Issue by honnix** [spotify/web-scripts#641]
`"@spotify/web-scripts": "^9.0.0"`

To repro:

Run `yarn web-scripts precommit --eslint-config .eslintrc`

It doesn't read `.eslintrc` but defaults to `node_modules/@spotify/web-scripts/config/eslintrc.js`. It seems this command option gets lost somewhere and because the file is not named as `.eslintrc.json` so https://github.com/spotify/web-scripts/blob/master/packages/web-scripts/src/Tasks/LintTask.ts#L29 couldn't find it and chooses the default one instead.

**Comment by honnix** [comment]
Maybe it can be `.eslintrc*` instead? Is it a regex or just file pattern?

**Comment by nickfryar** [comment]
I found that the opts for `precommit` are not being destructured correctly, so I opened a pull request for that [here](https://github.com/spotify/web-scripts/pull/699). It looks like it's still not picking up `.eslintrc` from my testing, though.

**Comment by yuriteixeira** [comment]
The [aforementioned fix](https://github.com/spotify/web-scripts/pull/699) was already merged. Shall we close this, @kaimallea?

**Comment by honnix** [comment]
> It looks like it's still not picking up .eslintrc from my testing, though.

Not sure that PR fixed this issue.

**Comment by yuriteixeira** [comment]
Hey @honnix! Soon enough we might be merging #925. Would you be so kind to try again whenever it gets merged?

**Comment by honnix** [comment]
@yuriteixeira Sure.
