### ISSUE TITLE
Add `--stylecheck` to `web-scripts lint`

### ISSUE THREAD

**Issue by fastfrwrd** [spotify/web-scripts#72]
Like the `--typecheck` option, `--stylecheck` will be an optional flag that, when passed to `web-scripts lint`, runs `prettier --check` on the `src` of the project.

**Comment by josephmcasey** [comment]
Would you be able to add some clarification around the specifications for this issue? I tried implementing this and ran into some uncertainty. How exactly should this interact with the preexisting ESLint configuration? Currently, running only prettier --check would cause lint conflicts with ESLint. You can see this in action by pulling down PR #76 .
