### ISSUE TITLE
web-scripts preinstall which runs yarn audit

### ISSUE THREAD

**Issue by fastfrwrd** [spotify/web-scripts#73]
Create a new hook script call `web-scripts preinstall`. It will run yarn audit and exit non-zero if the threshold is breached (`--threshold` will need to be an option for this command)

**Comment by josephmcasey** [comment]
Hey @fastfrwrd , I create the implementation for this issue. Before I write the tests, I wanted to get your opinion on my approach. Would you mind giving my PR a brief glance and letting me know if I should finish it up or change my direction?

**Comment by josephmcasey** [comment]
`web-scripts preinstall` shows `@spotify/web-scripts` has the following security vulnerabilities:

https://www.npmjs.com/advisories/1184
https://www.npmjs.com/advisories/1076
https://www.npmjs.com/advisories/1164

**Comment by fastfrwrd** [comment]
Fixed by #75
