### ISSUE TITLE
Enhancement - `web-scripts preinstall`

### ISSUE THREAD

**Issue by josephmcasey** [spotify/web-scripts#77]
I recently [read this article](https://snyk.io/blog/why-npm-lockfiles-can-be-a-security-blindspot-for-injecting-malicious-modules/) that [Snyk](https://snyk.io/) produced which goes into depth on why linting the lock files of package managers can be necessary to prevent the introduction of malicious code. The article references the use of a library similar to [lockfile-lint](https://github.com/lirantal/lockfile-lint/) as a solution to mitigate this problem.

How useful would builtin security features like this be for the users of this library?

**Comment by fastfrwrd** [comment]
fixed by #75
