### ISSUE TITLE
Should husky be marked as a (peer) dependency?

### ISSUE THREAD

**Issue by ekh64** [spotify/web-scripts#787]
Since `web-scripts commit` requires `husky`, I wonder if it should be marked in the `package.json` as a direct dependency or a peer dependency? Could someone install `@spotify/web-scripts` without husky and have it work as expected?

Since it's listed in the README instructions, I think it should be documented in the `package.json`

I'm happy to submit a PR, but wanted to see if there were opinions on your end before doing so.

**Comment by yuriteixeira** [comment]
It seems to make sense. What do you think @kaimallea?
