### ISSUE TITLE
[web-scripts] Using Docker for Testing Environment for git-dependent tasks

### ISSUE THREAD

**Issue by josephmcasey** [spotify/web-scripts#79]
## Type

Enhancement

## Summary

In my recent contribution I noticed that there area  number of [incomplete integration testing scenarios](https://github.com/spotify/web-scripts/blob/0c3b6870edeadcacbadfc73bea7183acdfb681f2/packages/web-scripts/src/integration.test.ts#L184-L203). I'd like to propose an enhancement to the overall testing strategy of this repository by using Docker to better simulate various developer setups and local machines.

## Reference

https://github.com/spotify/web-scripts/blob/master/packages/web-scripts/src/integration.test.ts#L184-L203

**Comment by fastfrwrd** [comment]
I totally agree that this would help - I have been thinking that splitting this up into separate task tests would be much easier to maintain, so I think we oughta do https://github.com/spotify/web-scripts/issues/104 before this, or as kind of a tandem effort.
