### ISSUE TITLE
Heads up only (no action required): Release 10.1.0 with Jest 27 might break tests with fake timers

### ISSUE THREAD

**Issue by yuriteixeira** [spotify/web-scripts#803]
We've noticed this failing test after bumping our web-scripts versions in our project: 

```
    expect(received).toHaveBeenCalled()

    Matcher error: received value must be a mock or spy function

    Received has type:  function
    Received has value: [Function clearTimeout]

      85 |
      86 |       (returnFn as Function)();
    > 87 |       expect(clearTimeout).toHaveBeenCalled();
         |                            ^
      88 |     });
      89 |   });
      90 |
```

That's due to [jest been upgraded to version 27](https://github.com/spotify/web-scripts/compare/v10.0.1...v10.1.0#diff-a9a771807338bd9ff638e21b6dde0e8fc80d4b991d1e958ae190655e8ce30600R50), which [caused a regression](https://github.com/facebook/jest/issues/11521).

The easiest mitigation for the issue is to use [`jest.useFakeTimers('legacy')`](https://jestjs.io/docs/jest-object#jestusefaketimersimplementation-modern--legacy) in the failing tests.

**Comment by kaimallea** [comment]
Sorry for the trouble! 10.1.0 should have been v11. I've fixed the publish pipeline and added this warning to the release notes. Thank you!! 🙏🏾
