### ISSUE TITLE
[web-scripts] Enable override configuration of style check path

### ISSUE THREAD

**Issue by PHjalmars** [spotify/web-scripts#841]
**Issue**
Currently the styleCheck will only check the src directory of the consuming root. 

We have a use case in which our project contains files we want styled checked in the root directory.

https://github.com/spotify/web-scripts/blob/b6469e5a6a84b389145576bba56adf70194f1c98/packages/web-scripts/src/Tasks/LintTask.ts
 
**Suggested enhancement**
Add an argument to override the path used for check.

**Comment by yuriteixeira** [comment]
Hey @PHjalmars! Would you like to take a stab and send us a PR implementing your suggestions?
