### ISSUE TITLE
Question:  Is there an npm project that contains the typescript interfaces for your web api?

### ISSUE THREAD

**Issue by SephReed** [spotify/web-scripts#843]
It's really easy to create typescript interfaces from json responses, so no worries if not.

But it really seems like this project exists somewhere and I just haven't found it yet.

All I'm looking for is interfaces.  Or better yet, a client.

**Comment by yuriteixeira** [comment]
Hello @SephReed 👋 Apparently there is: https://www.npmjs.com/package/@types/spotify-api
