### ISSUE TITLE
Prettier: /cjs, /esm & /types should be ignored

### ISSUE THREAD

**Issue by yuriteixeira** [spotify/web-scripts#959]
This happens because `web-scripts build` will generate `/esm/src`, `/cjs/src` & `/types/src`, making all of them match the `--check` glob pattern defined to run `prettier` with, therefore checking files it shouldn't be, since they are build artifacts.

See that happening in the code snippet below: 
https://github.com/spotify/web-scripts/blob/b6469e5a6a84b389145576bba56adf70194f1c98/packages/web-scripts/src/Tasks/LintTask.ts#L95

See also #841

**Comment by sonng** [comment]
I ran into a similar issue where my build artifacts was being picked up, i.e `/dist/src`. I got around this by creating a `.prettierignore` with the following

```
dist/
```

It seems to respect the `.prettierignore` over that code snippet.
